
# coding: utf-8

# # Problem 2: Even Fibonacci Terms
# 
# > This problem consists of just a single exercise, worth ten (10) points. This problem is the second of many on the site [Project Euler](http://www.projecteuler.net), a set of Number Theory-based computational problems. You might find some of the other problems to be fun challenges - but be warned, they scale up in difficulty quickly as you complete them!

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with `1` and `1`, the list of terms not exceeding `100` is:
#     
#         1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
#         
# That is, the next term, `55+89=144`, exceeds `100`, so we would stop at `89`.
# 
# Your computational task is to calculate the sum of the **even-valued** terms that are **less than** a given number. In this example, if the given number is `100`, then the sum of even-valued terms would be `2+8+34=44`.

# **Exercise 0** (10 points). Write a function, `even_fib_sum(n)`, that takes a specific value, `n`, as input, and returns the sum of the even-valued Fibonacci sequence terms that do not exceed `n`. 
# 
# For example:
#         
#         even_fib_sum(100) = 44 ( = 2 + 8 + 34)
#         even_fib_sum(200) = 188 ( = 2 + 8 + 34 + 144)
# 
# Keep in mind that we are not interested in the **nth** term in the sequence, but simply the Fibonacci numbers that are strictly less than `n`. 

# In[3]:


def even_fib_sum(n):
    a = 1
    b = 1
    totals = 0
    while b < n:
        if b % 2 == 0: #if b is even increment b
            totals += b
        a, b = b, a+b
    return totals

even_fib_sum(3)


# In[4]:


# Test cell: test_even_fib_sum

assert even_fib_sum(2) == 0, "even_fib_sum(2) did not correctly return 0."
assert even_fib_sum(3) == 2, "even_fib_sum(3) did not correctly return 2."
assert even_fib_sum(100) == 44, "even_fib_sum(100) did not correctly return 44."
assert even_fib_sum(1000000) == 1089154, "even_fib_sum(1000000) did not correctly return 1089154."
assert even_fib_sum(4000000) == 4613732, "even_fib_sum(4000000) did not correctly return 4613732."
print("\n(Passed!)")


# **Fin!** You've reached the end of this problem. Don't forget to restart the
# kernel and run the entire notebook from top-to-bottom to make sure you did
# everything correctly. If that is working, try submitting this problem. (Recall
# that you *must* submit and pass the autograder to get credit for your work!)
